name: Deploy Flutter Web to Firebase Hosting

on:
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: 3.35.2

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v395322a6cded4e9ed503aebd4cc1965625f8e59a
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Verify Flutter installation
        run: flutter --version

      # Flutter dependencies setup
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZZ_FLUTTER_WEB }}
          channelId: live
          projectId: quizz-flutter-web
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
