name: Deploy Flutter Web to Firebase Hosting

on:
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: 3.35.2

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Verify Flutter installation
        run: flutter --version

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Flutter dependencies setup
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZZ_FLUTTER_WEB }}
          channelId: live
          projectId: quizz-flutter-web
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
